[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "pandas",
    "cyvcf2",
    "igraph",
    "rpy2",
    "deap",
    "pytest",
    "pytest-datadir"
]
build-backend = "setuptools.build_meta"
