[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "pandas",
    "cyvcf2",
    "rpy2",
    "h5py",
    "deap",
    "scipy",
    "cvxpy",
    "matplotlib",
    "pytest",
    "pytest-datadir"
]
build-backend = "setuptools.build_meta"
